// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using System;
using System.Collections.Generic;
using VentasNet.Entity.Data.Configurations;
using VentasNet.Entity.Models;
#nullable disable

namespace VentasNet.Entity.Data
{
    public partial class VentasNetContext : DbContext
    {
        public VentasNetContext()
        {
        }

        public VentasNetContext(DbContextOptions<VentasNetContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Comprobante> Comprobante { get; set; }
        public virtual DbSet<FormaDePagos> FormaDePagos { get; set; }
        public virtual DbSet<MovimientosDeComprobantes> MovimientosDeComprobantes { get; set; }
        public virtual DbSet<MovimientosDeProveedores> MovimientosDeProveedores { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Proveedor> Proveedor { get; set; }
        public virtual DbSet<Stock> Stock { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<VwComprobantes> VwComprobantes { get; set; }
        public virtual DbSet<VwUsuario> VwUsuario { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new Configurations.ClienteConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ComprobanteConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.FormaDePagosConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.MovimientosDeComprobantesConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.MovimientosDeProveedoresConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ProductoConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ProveedorConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.StockConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.UsuarioConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.VwComprobantesConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.VwUsuarioConfiguration());

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
