// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using VentasNet.Entity.Data;
using VentasNet.Entity.Models;

namespace VentasNet.Entity.Data.Configurations
{
    public partial class ClienteConfiguration : IEntityTypeConfiguration<Cliente>
    {
        public void Configure(EntityTypeBuilder<Cliente> entity)
        {
            entity.HasKey(e => e.IdCliente);

            entity.Property(e => e.Apellido)
                .HasMaxLength(50)
                .IsFixedLength();

            entity.Property(e => e.Cuil)
                .HasMaxLength(11)
                .HasColumnName("CUIL")
                .IsFixedLength();

            entity.Property(e => e.Domicilio)
                .IsRequired()
                .HasMaxLength(100)
                .IsFixedLength();

            entity.Property(e => e.FechaAlta).HasColumnType("datetime");

            entity.Property(e => e.FechaBaja).HasColumnType("datetime");

            entity.Property(e => e.IdUsuario).HasColumnName("idUsuario");

            entity.Property(e => e.Localidad)
                .IsRequired()
                .HasMaxLength(50)
                .IsFixedLength();

            entity.Property(e => e.Nombre)
                .HasMaxLength(50)
                .IsFixedLength();

            entity.Property(e => e.Provincia)
                .IsRequired()
                .HasMaxLength(50)
                .IsFixedLength();

            entity.Property(e => e.RazonSocial)
                .HasMaxLength(100)
                .IsFixedLength();

            entity.Property(e => e.Telefono)
                .IsRequired()
                .HasMaxLength(15)
                .IsFixedLength();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Cliente> entity);
    }
}
