// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using VentasNet.Entity.Data;
using VentasNet.Entity.Models;

namespace VentasNet.Entity.Data.Configurations
{
    public partial class MovimientosDeComprobantesConfiguration : IEntityTypeConfiguration<MovimientosDeComprobantes>
    {
        public void Configure(EntityTypeBuilder<MovimientosDeComprobantes> entity)
        {
            entity.Property(e => e.Id).HasColumnName("id");

            entity.Property(e => e.Descuento).HasColumnType("decimal(16, 2)");

            entity.Property(e => e.IdComprobante).HasColumnName("idComprobante");

            entity.Property(e => e.Importe).HasColumnType("decimal(16, 2)");

            entity.Property(e => e.Total).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.IdComprobanteNavigation)
                .WithMany(p => p.MovimientosDeComprobantes)
                .HasForeignKey(d => d.IdComprobante)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MovimientosDeComprobantes_Comprobante");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<MovimientosDeComprobantes> entity);
    }
}
