// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using VentasNet.Entity.Data;
using VentasNet.Entity.Models;

namespace VentasNet.Entity.Data.Configurations
{
    public partial class MovimientosDeProveedoresConfiguration : IEntityTypeConfiguration<MovimientosDeProveedores>
    {
        public void Configure(EntityTypeBuilder<MovimientosDeProveedores> entity)
        {
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.Comprobante)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.Descuentos).HasColumnType("decimal(16, 2)");

            entity.Property(e => e.FechaComprobante).HasColumnType("date");

            entity.Property(e => e.FechaMovimiento)
                .IsRequired()
                .IsRowVersion()
                .IsConcurrencyToken();

            entity.Property(e => e.ImporteTotal).HasColumnType("decimal(16, 2)");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<MovimientosDeProveedores> entity);
    }
}
