// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using VentasNet.Entity.Data;
using VentasNet.Entity.Models;

namespace VentasNet.Entity.Data.Configurations
{
    public partial class VwComprobantesConfiguration : IEntityTypeConfiguration<VwComprobantes>
    {
        public void Configure(EntityTypeBuilder<VwComprobantes> entity)
        {
            entity.HasNoKey();

            entity.ToView("vwComprobantes");

            entity.Property(e => e.IdComprobante)
                .ValueGeneratedOnAdd()
                .HasColumnName("idComprobante");

            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.NombreCorto)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VwComprobantes> entity);
    }
}
