// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VentasNet.Entity.Models
{
    public partial class VwComprobantes
    {
        public int IdComprobante { get; set; }
        public string Nombre { get; set; }
        public string NombreCorto { get; set; }
        public int? NroUltimoCbte { get; set; }
    }
}